### ISSUE TITLE
Not an issue but didn't know where to leave this. Modded blocks dump

### ISSUE THREAD

**Issue by AvrgDerk** [EuphoriaPatches/propertiesFiles#11]
These are block ids I've added to complementary shaders and other older shaderpacks for a few years. I've slowly added blocks as needed to my own modpacks in the block.properties file but figure they may be used best over here. They're from different mods and may not be very organized. I'm just copying and contributing these if they can be of any help :-)

block.10005=grass short_grass fern oak_sapling spruce_sapling birch_sapling jungle_sapling acacia_sapling dark_oak_sapling bamboo_sapling cherry_sapling dead_bush dandelion poppy blue_orchid allium azure_bluet red_tulip orange_tulip white_tulip pink_tulip oxeye_daisy cornflower lily_of_the_valley wither_rose sweet_berry_bush wheat carrots potatoes beetroots pumpkin_stem melon_stem nether_sprouts warped_roots crimson_roots sunflower:half=lower lilac:half=lower rose_bush:half=lower peony:half=lower tall_grass:half=lower large_fern:half=lower torchflower_crop biomesoplenty:dune_grass biomesoplenty:dead_grass biomesoplenty:desert_grass biomesoplenty:sprout biomesoplenty:bush biomesoplenty:rose biomesoplenty:violet biomesoplenty:lavender biomesoplenty:wildflower biomesoplenty:orange_cosmos biomesoplenty:pink_daffodil biomesoplenty:pink_hibiscus biomesoplenty:glowflower biomesoplenty:wilted_lily biomesoplenty:burning_blossom biomesoplenty:toadstool farmersdelight:wild_cabbages farmersdelight:wild_onions farmersdelight:wild_tomatoes farmersdelight:wild_carrots farmersdelight:wild_potatoes farmersdelight:wild_beetroots biomesoplenty:origin_sapling biomesoplenty:flowering_oak_sapling biomesoplenty:rainbow_birch_sapling biomesoplenty:yellow_autumn_sapling biomesoplenty:orange_autumn_sapling biomesoplenty:maple_sapling biomesoplenty:fir_sapling biomesoplenty:redwood_sapling biomesoplenty:white_cherry_sapling biomesoplenty:pink_cherry_sapling biomesoplenty:mahogany_sapling biomesoplenty:jacaranda_sapling biomesoplenty:palm_sapling biomesoplenty:willow_sapling biomesoplenty:dead_sapling biomesoplenty:magic_sapling biomesoplenty:umbran_sapling biomesoplenty:hellbark_sapling biomesoplenty:barley:half=lower biomesoplenty:goldenrod:half=lower biomesoplenty:blue_hydrangea:half=lower biomesoplenty:watergrass:half=lower biomesoplenty:reed:half=lower biomesoplenty:cattail:half=lower biomesoplenty:sea_oats:half=lower biomesoplenty:tall_lavender:half=lower biomesoplenty:icy_iris:half=lower farmersdelight:wild_rice:half=lower twilightforest:fiddlehead twilightforest:twilight_oak_sapling twilightforest:canopy_sapling twilightforest:mangrove_sapling twilightforest:darkwood_sapling twilightforest:hollow_oak_sapling twilightforest:time_sapling twilightforest:transformation_sapling twilightforest:mining_sapling twilightforest:sorting_sapling twilightforest:rainbow_oak_sapling blue_skies:turquoise_grass blue_skies:tall_turquoise_grass:half=lower blue_skies:snowcap_mushroom:half=lower blue_skies:tall_lunar_grass:half=lower blue_skies:camellia blue_skies:snowbloom blue_skies:blush_blossom blue_skies:polar_posy blue_skies:chillweed blue_skies:brittlebush blue_skies:briskbloom blue_skies:frose blue_skies:midday_bishop blue_skies:bluebright_sapling blue_skies:starlit_sapling blue_skies:frostbright_sapling blue_skies:brewberry_bush blue_skies:snowcap_pinhead blue_skies:lunar_grass blue_skies:moonlit_bloom blue_skies:crystal_flower blue_skies:blaze_bud blue_skies:flare_floret blue_skies:nightcress blue_skies:muckweed blue_skies:lucentroot blue_skies:lunar_sapling blue_skies:dusk_sapling blue_skies:maple_sapling blue_skies:baneful_mushroom blue_skies:glimmer_reed blue_skies:crystallized_grass blue_skies:crescent_fruit_sapling corn_delight:wild_corn upgrade_aquatic:blue_pickerelweed upgrade_aquatic:purple_pickerelweed upgrade_aquatic:river_sapling upgrade_aquatic:beachgrass upgrade_aquatic:white_searocket upgrade_aquatic:pink_searocket buzzier_bees:buttercup buzzier_bees:white_clover buzzier_bees:pink_clover upgrade_aquatic:flowering_rush:half=lower upgrade_aquatic:tall_beachgrass:half=lower upgrade_aquatic:tall_blue_pickerelweed:half=lower upgrade_aquatic:tall_purple_pickerelweed:half=lower supplementaries:wild_flax ecologics:walnut_sapling ecologics:azalea_sapling undergarden:amorous_bristle undergarden:miserabell undergarden:butterbunch alexscaves:ancient_sapling alexscaves:pewen_branch alexscaves:pewen_sapling alexscaves:pewen_pines alexscaves:fiddlehead alexscaves:archaic_vine alexscaves:tree_star biomemakeover:purple_glowshroom biomemakeover:green_glowshroom biomemakeover:orange_glowshroom biomemakeover:mycelium_sprouts biomemakeover:mycelium_roots biomemakeover:blighted_balsa_sapling biomemakeover:barrel_cactus biomemakeover:barrel_cactus_flowered biomemakeover:willow_sapling biomemakeover:swamp_cypress_sapling biomemakeover:ancient_oak_sapling theabyss:icora_flower biomemakeover:reed:half=lower biomemakeover:cattail:half=lower biomemakeover:tall_red_mushroom:half=lower  biomemakeover:tall_brown_mushroom:half=lower alexscaves:curly_fern:half=lower biomemakeover:buttonbush:half=lower biomemakeover:marigold:half=lower biomemakeover:black_thistle:half=lower biomemakeover:foxglove:half=lower deep_aether:tall_aether_cattails:half=lower deep_aether:tall_golden_grass:half=lower deep_aether:tall_feather_grass:half=lower lost_aether_content:holiday_sapling ancient_aether:sky_grass aether:berry_bush_stem deep_aether:squash_seeds aether:berry_bush aether_redux:zanberry_bush_stem deep_aether:lightcap_mushrooms aether:purple_flower ancient_aether:highland_viola aether:white_flower aether_redux:wyndsprouts aether_redux:skysprouts aether_redux:fieldsproot_petals aether_redux:iridia aether_redux:xaelia_flowers aether_redux:aurum aether_redux:golden_clover aether_redux:zyatrix aether_redux:luxweed aether_redux:spirolyctil aether_redux:blightshade aether_redux:lumina aether_redux:daggerbloom aether_redux:theratip aether_redux:cloudcap_mushling aether_redux:jellyshroom aether_redux:shimmerstool ancient_aether:sky_blues ancient_aether:wynd_thistle ancient_aether:sakura_blossoms ancient_aether:trapped_sakura_blossoms deep_aether:radiant_orchid deep_aether:aerlavender deep_aether:tall_aerlavender:half=lower deep_aether:aether_cattails deep_aether:golden_flower deep_aether:enchanted_blossom deep_aether:feather_grass deep_aether:sky_tulips deep_aether:iaspove deep_aether:golden_aspess deep_aether:echaisy deep_aether:mini_golden_grass deep_aether:short_golden_grass deep_aether:medium_golden_grass aether_redux:short_aether_grass aether_redux:splitfern aether_redux:avelium_sprouts aether_redux:avelium_roots aether:skyroot_sapling ancient_aether:crystal_skyroot_sapling ancient_aether:enchanted_skyroot_sapling aether:golden_oak_sapling aether_redux:blightwillow_sapling aether_redux:blighted_skyroot_sapling aether_redux:glacia_sapling aether_redux:purple_glacia_sapling aether_redux:gilded_oak_sapling aether_redux:crystal_sapling aether_redux:crystal_fruit_sapling aether_redux:fieldsproot_sapling ancient_aether:skyroot_pine_sapling ancient_aether:highsproot_sapling ancient_aether:sakura_sapling deep_aether:roseroot_sapling deep_aether:blue_roseroot_sapling deep_aether:yagroot_sapling deep_aether:cruderoot_sapling deep_aether:conberry_sapling deep_aether:sunroot_sapling theabyss:loran_flower:half=lower theabyss:gulom_plant theabyss:ralom_plant theabyss:fortris_ultima theabyss:thunder_flower theabyss:srala_shroom theabyss:saturnia_versa theabyss:caecus_versa theabyss:tall_glow_shroom:half=lower theabyss:glow_shroom:half=lower theabyss:tall_rub_shroom:half=lower theabyss:rub_shroom:half=lower theabyss:exolius_plant theabyss:young_exolius_plant theabyss:vigilant_grass theabyss:vigilant_blue_grass theabyss:vigilant_outer_leaves theabyss:vigilant_blue_outer_leaves theabyss:blaru_grass theabyss:tall_blaru_grass:half=lower the_deep_void:rotten_grass:half=lower theabyss:slimed_grass the_deep_void:bone_marrow the_deep_void:cave_growth alexscaves:underweed alexscaves:thornwood_sapling alexscaves:bone_worms biomesoplenty:high_grass_plant

block.10009=leaves leaves2 oak_leaves spruce_leaves birch_leaves jungle_leaves acacia_leaves dark_oak_leaves azalea_leaves flowering_azalea_leaves mangrove_leaves cherry_leaves biomesoplenty:origin_leaves biomesoplenty:flowering_oak_leaves biomesoplenty:rainbow_birch_leaves biomesoplenty:yellow_autumn_leaves biomesoplenty:orange_autumn_leaves biomesoplenty:maple_leaves biomesoplenty:fir_leaves biomesoplenty:redwood_leaves biomesoplenty:mahogany_leaves biomesoplenty:palm_leaves biomesoplenty:willow_leaves biomesoplenty:dead_leaves biomesoplenty:magic_leaves biomesoplenty:umbran_leaves biomesoplenty:hellbark_leaves biomesoplenty:pink_cherry_leaves biomesoplenty:white_cherry_leaves biomesoplenty:jacaranda_leaves quark:blue_blossom_leaves quark:lavender_blossom_leaves quark:orange_blossom_leaves quark:pink_blossom_leaves quark:yellow_blossom_leaves blue_skies:bluebright_leaves blue_skies:starlit_leaves blue_skies:frostbright_leaves blue_skies:lunar_leaves blue_skies:dusk_leaves blue_skies:maple_leaves blue_skies:crystallized_leaves blue_skies:cherry_leaves blue_skies:crescent_fruit_leaves twilightforest:beanstalk_leaves twilightforest:giant_leaves twilightforest:thorn_leaves twilightforest:twilight_oak_leaves twilightforest:canopy_leaves twilightforest:mangrove_leaves twilightforest:darkwood_leaves twilightforest:time_leaves twilightforest:transformation_leaves twilightforest:mining_leaves twilightforest:sorting_leaves twilightforest:rainbow_oak_leaves upgrade_aquatic:river_leaves ecologics:walnut_leaves undergarden:grongle_leaves alexscaves:ancient_leaves biomemakeover:blighted_balsa_leaves biomemakeover:willow_leaves biomemakeover:swamp_cypress_leaves biomemakeover:ancient_oak_leaves aether_redux:zanberry_bush aether:skyroot_leaves ancient_aether:crystal_skyroot_leaves ancient_aether:enchanted_skyroot_leaves aether:golden_oak_leaves aether_redux:golden_leaf_pile aether_redux:gilded_oak_leaves aether_redux:gilded_leaf_pile ancient_aether:skyroot_pine_leaves ancient_aether:highsproot_leaves ancient_aether:sakura_leaves aether_redux:blightwillow_leaves aether_redux:blightwillow_leaf_pile aether_redux:blighted_skyroot_leaves aether_redux:glacia_leaves aether_redux:purple_glacia_leaves aether:holiday_leaves aether:decorated_holiday_leaves aether_redux:fieldsproot_leaves deep_aether:roseroot_leaves deep_aether:flowering_roseroot_leaves deep_aether:blue_roseroot_leaves deep_aether:flowering_blue_roseroot_leaves deep_aether:yagroot_leaves deep_aether:cruderoot_leaves deep_aether:conberry_leaves deep_aether:sunroot_leaves theabyss:blaru_leaves theabyss:jungle_leaves theabyss:frozen_leaves twilightforest:fallen_leaves

block.10013=vine biomesoplenty:willow_vine blue_skies:bluebright_vine blue_skies:starlit_vine blue_skies:frostbright_vine blue_skies:lunar_vine blue_skies:dusk_vine blue_skies:maple_vine undergarden:hanging_grongle_leaves biomemakeover:willowing_branches deep_aether:sunroot_hanger aether_redux:golden_vines aether_redux:gilded_vines twilightforest:root_strand twilightforest:trollvidr twilightforest:unripe_trollber twilightforest:trollber deep_aether:yagroot_vine

block.10017=reeds attached_pumpkin_stem attached_melon_stem mangrove_propagule seagrass tall_seagrass kelp_plant kelp hanging_roots sugar_cane spore_blossom pink_petals pitcher_plant cobweb blue_skies:sea_moss blue_skies:brumble blue_skies:brumble_vine_top

block.10021=double_plant:half=upper sunflower:half=upper lilac:half=upper rose_bush:half=upper peony:half=upper tall_grass:half=upper large_fern:half=upper farmersdelight:wild_rice:half=upper biomesoplenty:barley:half=upper biomesoplenty:goldenrod:half=upper biomesoplenty:blue_hydrangea:half=upper biomesoplenty:blue_hydrangea:half=upper biomesoplenty:reed:half=upper biomesoplenty:cattail:half=upper blue_skies:tall_turquoise_grass:half=upper blue_skies:snowcap_mushroom:half=upper blue_skies:tall_lunar_grass:half=upper biomesoplenty:watergrass:half=upper biomesoplenty:sea_oats:half=upper biomesoplenty:tall_lavender:half=upper biomesoplenty:icy_iris:half=upper upgrade_aquatic:flowering_rush:half=upper upgrade_aquatic:tall_beachgrass:half=upper upgrade_aquatic:tall_blue_pickerelweed:half=upper upgrade_aquatic:tall_purple_pickerelweed:half=upper biomemakeover:cattail:half=upper biomemakeover:reed:half=upper biomemakeover:cattail:half=upper biomemakeover:tall_red_mushroom:half=upper biomemakeover:tall_brown_mushroom:half=upper alexscaves:curly_fern:half=upper biomemakeover:buttonbush:half=upper biomemakeover:marigold:half=upper biomemakeover:black_thistle:half=upper biomemakeover:foxglove:half=upper deep_aether:tall_aether_cattails:half=upper deep_aether:tall_golden_grass:half=upper deep_aether:tall_feather_grass:half=upper deep_aether:tall_aerlavender:half=upper theabyss:loran_flower:half=upper theabyss:tall_glow_shroom:half=upper theabyss:glow_shroom:half=upper theabyss:tall_rub_shroom:half=upper theabyss:rub_shroom:half=upper theabyss:tall_blaru_grass:half=upper the_deep_void:rotten_grass:half=upper biomesoplenty:high_grass

block.10328=amethyst_block budding_amethyst biomemakeover:illunite_block biomemakeover:budding_illunite

block.10332=small_amethyst_bud medium_amethyst_bud large_amethyst_bud amethyst_cluster biomemakeover:illunite_cluster biomemakeover:large_illunite_bud biomemakeover:medium_illunite_bud biomemakeover:small_illunite_bud

**Comment by SpacEagle17** [comment]
Thank you very much!
I'll organize them myself and add them to the files :)
